version: '2'

services:
  elasticsearch:
    image: elasticsearch:latest
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - esnet
  web:
    build: .
    hostname: products_api
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/product-api
    depends_on:
      - elasticsearch
    networks:
      - esnet
networks:
  esnet:
    driver: bridge
