version: '2'

services:
  elasticsearch:
    image: elasticsearch:latest
    ports:
      - "9200:9200"
      - "9300:9300"
  web:
    build: .
    command: python -u app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/todo
    links:
      - elasticsearch
